# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:http://localhost:3000"
ip-from-header: "_env:IP_FROM_HEADER:false"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

database:
  database: "_env:SQLITE_DATABASE:weixin-mp-sdk-demo.sqlite3"
  poolsize: "_env:SQLITE_POOLSIZE:10"

copyright: Insert copyright statement here
#analytics: UA-YOURCODE

wxpp:
  app-id: "_env:WXPP_APP_ID:wx5961c4d11d66a53c"
  secret: "_env:WXPP_SECRET:172947fa370ddeae040f9a06a11342b1"
  token: "_env:kXPP_TOKEN:testtoken"
  aes-key:
    - "_env:WXPP_AES_KEY:WJmA6ZeDKg3yVYf4iuVmksKjFZdfZqbnliig6iUfpJf="
    - "_env:WXPP_AES_KEY2:"

wxpp-data-dir   : "_env:WXPP_DATA_DIR:demo-data"

acid:
  connect: "_env:ACID_CONNECT:state"
