Default: &defaults
  database: weixin-mp-sdk-demo.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: weixin-mp-sdk-demo_test.sqlite3
  <<: *defaults

Staging:
  database: weixin-mp-sdk-demo_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: weixin-mp-sdk-demo_production.sqlite3
  poolsize: 100
  <<: *defaults
